### ISSUE TITLE
The tissue specific genes in database

### ISSUE THREAD

**Issue by wjyzidane** [Tuteja-Lab/TissueEnrich#1]
I found although many genes are identified as tissue-specific in my list, there is no significant P-value. I guess the number of tissue-specific genes in that category is very large. But is there any way I can check the number or the genes in each tissue-specific genes category? Thanks!

**Comment by ashishjain1988** [comment]
The tissue-specific gene enrichment is carried out by using the hypergeometric test which is not biased towards the total number of the tissue-specific genes. For more information, you can read through the vignette of the package. We don't provide the total number of tissue-specific genes or the number but it can be calculated by looking through the inst/extdata/combine-expression.rda R object in the package which contains the information about all the tissue-specific genes.

**Comment by ashishjain1988** [comment]
For future questions or queries related to TissueEnrich package, please post on the Bioconductor support website. This will help us to build an information repository which can be used by other users (https://support.bioconductor.org).

**Comment by wjyzidane** [comment]
Got it. Thanks!
